config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en/ do
    root to: 'frontend#index'

    get 'discover', to: 'frontend#discover'

    get 'diving', to: 'frontend#diving'

    get 'fishing', to: 'frontend#fishing'

    get 'kiteboarding', to: 'frontend#kiteboarding'

    get ':section/reservation/:code/:accomodation', to: 'frontend#reservation'

    post 'reserve', to: 'reservations#create'

    get 'price_activity/:name', to: 'reservations#price_activity'

    devise_for :users, skip: KepplerConfiguration.skip_module_devise

    mount KepplerContactUs::Engine, :at => '/', as: 'messages'

    mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'

    resources :admin, only: :index

    scope :admin do

      resources :legal_terms do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :rooms do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      get 'discount/:code', to: 'discounts#by_code', as: :discount_by_code
      resources :discounts do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

    	resources :users do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :quotes do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :activities do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :packages do
        resources :offers do
          get '(page/:page)', action: :index, on: :collection, as: ''
          delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
        end
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :reservations, except: :create do
        get '/charge', to: 'reservations#create_charge'
        get '/cancel', to: 'reservations#cancel_charge'
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :customers do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end
    end


    #errors
    match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
    match '/404', to: 'errors#not_found', via: :all
    match '/422', to: 'errors#unprocessable', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all


    #dashboard
    mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'
  end
end

app/models/quote.rb
#Generado por keppler
require 'elasticsearch/model'
class Quote < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:title, :country, :client] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      title:  self.title.to_s,
      quote:  self.quote.to_s,
      client:  self.client.to_s,
      country:  self.country.to_s,
    }.as_json
  end

end
#Quote.import

app/controllers/quotes_controller.rb
#Generado con Keppler.
class QuotesController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  def index
    quotes = Quote.searching(@query).all
    @objects, @total = quotes.page(@current_page), quotes.size
    redirect_to quotes_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /quotes/1
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      redirect_to @quote, notice: 'Quote was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /quotes/1
  def update
    if @quote.update(quote_params)
      redirect_to @quote, notice: 'Quote was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /quotes/1
  def destroy
    @quote.destroy
    redirect_to quotes_url, notice: 'Quote was successfully destroyed.'
  end

  def destroy_multiple
    Quote.destroy redefine_ids(params[:multiple_ids])
    redirect_to quotes_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def quote_params
      params.require(:quote).permit(:title, :quote, :client, :country)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.format_quote.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Un sistema de manejo y control de los testimonios integrado a Keppler-Admin. Cada testimonio es realizados por los turistas de Los Roques y recolectado por Oceanica para dar a conocer las maravillas de este lugar magico.

app/views/quotes/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to quotes_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @quote do |f|
					.row
						= f.input :title
						= f.input :quote, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }
						= f.input :client
						= f.input :country

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/quotes/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Quote
			= link_to edit_quote_path(@quote), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.format_quote.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.title")
			.display-value= @quote.title
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.quote")
			.display-value= @quote.quote.html_safe
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.client")
			.display-value= @quote.client
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.country")
			.display-value= @quote.country
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/quotes/_listing.html.haml
%tr{ id: "row-#{quote.id}" }
	- if can? :destroy_multiple, Quote
		%td.item-check{style:"width: 10%"}
			= link_to "", quote_path(quote), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{quote.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{quote.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{quote.id}" }
		%td{style:"width: 30%"}
			= link_to "", quote_path(quote, search: @query), remote: true, class: "show-row"
			%span
				= quote.client
		%td{style:"width: 30%"}
			= link_to "", quote_path(quote, search: @query), remote: true, class: "show-row"
			%span
				= quote.country
								
	%td{style:"width: 5%"}		
		= link_to quote_path(quote), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/quotes/edit.html.haml
= title "Quotes - editar | #{@quote.id}"
= render 'form'

app/views/quotes/index.html.haml
= title("Quotes - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_quote_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |quote|
				= render 'listing', quote: quote
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado quotes.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_quote_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/quotes/new.html.haml
= title "Quotes - Nuevo"
= render 'form'

app/views/quotes/show.html.haml
= title "Quotes | #{@quote.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Quote
				= link_to quote_path(@quote), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Quote
				= link_to edit_quote_path(@quote), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to quotes_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.title")
					.display-value.fs-body-1.tc-black-2= @quote.title.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.quote")
					.display-value.fs-body-1.tc-black-2= @quote.quote.html_safe
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.client")
					.display-value.fs-body-1.tc-black-2= @quote.client.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.country")
					.display-value.fs-body-1.tc-black-2= @quote.country.to_s.humanize

app/views/quotes/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@quote.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");