config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en/ do
    root to: 'frontend#index'

    get 'discover', to: 'frontend#discover'

    get 'diving', to: 'frontend#diving'

    get 'fishing', to: 'frontend#fishing'

    get 'kiteboarding', to: 'frontend#kiteboarding'

    get ':section/reservation/:code/:accomodation', to: 'frontend#reservation'

    post 'reserve', to: 'reservations#create'

    get 'price_activity/:name', to: 'reservations#price_activity'

    devise_for :users, skip: KepplerConfiguration.skip_module_devise

    mount KepplerContactUs::Engine, :at => '/', as: 'messages'

    mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'

    resources :admin, only: :index

    scope :admin do

      resources :legal_terms do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :rooms do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      get 'discount/:code', to: 'discounts#by_code', as: :discount_by_code
      resources :discounts do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

    	resources :users do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :quotes do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :activities do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :packages do
        resources :offers do
          get '(page/:page)', action: :index, on: :collection, as: ''
          delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
        end
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :reservations, except: :create do
        get '/charge', to: 'reservations#create_charge'
        get '/cancel', to: 'reservations#cancel_charge'
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :customers do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end
    end


    #errors
    match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
    match '/404', to: 'errors#not_found', via: :all
    match '/422', to: 'errors#unprocessable', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all


    #dashboard
    mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'
  end
end

app/models/keppler_catalogs/attachment.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerCatalogs
  class Attachment < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    belongs_to :catalog
    belongs_to :category
    before_save :create_permalink
    before_save :url_iframe_service    
    before_update :update_uploads
    after_update :remove_image_public
    mount_uploader :image, CoverUploader
    validates_presence_of :category_id, :name, :upload

    
    after_commit on: [:update] do
      puts __elasticsearch__.index_document
    end

    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:name, :description, :category, :public] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        name:  self.name,
        description: ActionView::Base.full_sanitizer.sanitize(self.description, tags: []),
        public:  self.public ? "publicado" : "no--publicado"
      }.as_json
    end

    def create_permalink
      self.permalink = self.name.downcase.parameterize
    end

    def remove_image_public
      if !self.image_url.nil? and self.upload != "1"
        image = File.dirname(Rails.root.join("public"+self.image_url))
        FileUtils.rm_rf(image)
      end
    end
    

    def url_iframe_service
      if !self.url.blank?
        video = self.detected_video_service
        begin
          case video.keys.first
            when "youtube"
              self.url="https://www.youtube.com/embed/"+video.values.first
            when "vimeo"
              self.url="https://player.vimeo.com/video/"+video.values.first
            when "soundcloud"
              detected_soundcloud_sets              
            when "imagen"
            else
              self.url=""
            end
        rescue
          self.url=""
        end
      end
    end

    def detected_soundcloud_sets
      client = Soundcloud.new(:client_id => 'YOUR_CLIENT_ID')
      begin
        track = client.get('/resolve', :url => self.url)
        if self.url.split(/\W+/).include?("sets")
          self.url="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/#{track.id}&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"
        else
          self.url="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/#{track.id}&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"
        end 
      rescue Soundcloud::ResponseError => e
        
      end
    end

    def detected_video_service
      if self.upload == "2"
        {"imagen"=>""}
      else
        ["youtube", "soundcloud", "vimeo"].each do |service|    
          if service == "vimeo"
            return { service=>self.url.split("/").last }
          else         
            return { service=>self.url.split((/([\w-]{11})/)).last } if self.url.split(/\W+/).include?(service)
          end
        end      
      end
    end

    def update_uploads
      if self.upload == "1"
        self.url = ""
      else
        self.remove_image!
      end   
    end

  end
  #Attachment.import
end

app/views/keppler_catalogs/catalogs/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.perm_media.css_class("md-light") 
		= "Galerías"
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 
			= t("model.#{controller_name.singularize}.description.title")
		%p{align:"justify"} 
			Un sistema de manejo y control de las distintas galerias de Oceanica integrado a Keppler-Admin. Este módulo puede almacenar y ordenar imágenes de los paisajes y expereriencias en Los Roques.

app/views/keppler_catalogs/catalogs/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to catalogs_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @catalog do |f|
					.row
					
						= f.input :cover, label: t("model.#{controller_name.singularize}.attributes.cover"), :as => :file_material, label: false, wrapper_html: { class: "file-field" }
						= f.input :name, label: t("model.#{controller_name.singularize}.attributes.name")								
						= f.input :description, label: t("model.#{controller_name.singularize}.attributes.description"), :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }
						= f.input :section, label: t("model.#{controller_name.singularize}.attributes.section"), label: false, collection: KepplerCatalogs.sections,include_blank: "- Selecciona una sección -", input_html: { class: "browser-default" }
						= f.input :public, label: t("model.#{controller_name.singularize}.attributes.public"), as: :checkbox_material

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"
- if @catalog.cover.file
	:javascript
		$('.file-path').val("#{@catalog.cover}")

app/views/keppler_catalogs/catalogs/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :index, KepplerCatalogs::Attachment
			= link_to catalog_attachments_path(@catalog), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Ir a archivos", "data-no-turbolink" => false do
				= material_icon.md_24.perm_media
		- if can? :update, KepplerCatalogs::Catalog
			= link_to edit_catalog_path(@catalog), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink" => true do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.perm_media.css_class("md-light") 
		= "Galerías"
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	- if @catalog.attachments.last.image?
		= image_tag @catalog.attachments.last.image 
	- else
		= image_tag @catalog.attachments.last.url
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @catalog.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.section")
			.display-value= @catalog.section
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.public")
			.display-value= @catalog.public? ? "Si" : "No"
		%li.list-row
			.display-label Archivos contenidos
			.display-value= @catalog.attachments.count
	

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/keppler_catalogs/catalogs/_listing.html.haml
%tr{ id: "row-#{catalog.id}" }
	- if can? :destroy_multiple, model
		%td.item-check{style:"width: 10%"}
			= link_to "", catalog_path(catalog), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{catalog.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{catalog.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{catalog.id}" }

	%td{style:"width: 10%"}
		= link_to "", catalog_path(catalog, search: @query), remote: true, class: "show-row"
		%span
			= material_icon.md_24.folder_open
	%td{style:"width: 30%"}
		= link_to "", catalog_path(catalog, search: @query), remote: true, class: "show-row"
		%span
			= catalog.name
	%td{style:"width: 30%"}
		= link_to "", catalog_path(catalog, search: @query), remote: true, class: "show-row"
		%span
			= catalog.section
	%td{style:"width: 30%"}
		= link_to "", catalog_path(catalog, search: @query), remote: true, class: "show-row"
		%span= catalog.public? ? "Publicado" : "No publicado"
								
	%td{style:"width: 5%"}
		= link_to "#", class: "btn-floating waves-effect waves-light btn-flat dropdown-button", "data-activates" => "catalog-options-#{catalog.id}" do
			= material_icon.md_24.more_vert.css_class("md-dark")
		%ul{ id: "catalog-options", class: "dropdown-content dropdow-content-listing", id: "catalog-options-#{catalog.id}"}
			%li
				= link_to 'Ver detallado', catalog_path(catalog)
			%li
				= link_to 'Ir a archivos', catalog_attachments_path(catalog)
					
					
		

app/views/keppler_catalogs/catalogs/edit.html.haml
= title "Galerías - editar | #{@catalog.id}"
= render 'form'

app/views/keppler_catalogs/catalogs/index.html.haml
= title("Galerías - Listado")

= header_information do
	= "Galerías"
.listing.col.l9.m12.s12
	- if can? :new, KepplerCatalogs::Catalog
		= link_to new_catalog_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
		= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |catalog|
				= render 'listing', catalog: catalog
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t("model.#{controller_name.singularize}.no_found.text")
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, KepplerCatalogs::Catalog
	= link_to new_catalog_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/keppler_catalogs/catalogs/new.html.haml
= title "Galerías - Nuevo"
= render 'form'

app/views/keppler_catalogs/catalogs/show.html.haml
= title "Galerías | #{@catalog.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, model
				= link_to catalog_path(@catalog), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: '¿Estas seguro de querer eliminar?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, model
				= link_to edit_catalog_path(@catalog), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink" => true do
					= material_icon.md_18.create.css_class("md-dark")
			- if can? :index, KepplerCatalogs::Attachment
				= link_to catalog_attachments_path(@catalog), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Ir a archivos" do
					= material_icon.md_18.perm_media.css_class("md-dark")	
			= link_to catalogs_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card{style: "padding: 0px"}		
			.card-image
				= image_tag @catalog.cover	
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.name")
						.display-value.fs-body-1.tc-black-2= @catalog.name.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.description")
						.display-value.fs-body-1.tc-black-2= @catalog.description.html_safe
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.section")
						.display-value.fs-body-1.tc-black-2= @catalog.section.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.public")
						.display-value.fs-body-1.tc-black-2= @catalog.public? ? "Si" : "No"

app/views/keppler_catalogs/catalogs/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@catalog.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");