config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en/ do
    root to: 'frontend#index'

    get 'discover', to: 'frontend#discover'

    get 'diving', to: 'frontend#diving'

    get 'fishing', to: 'frontend#fishing'

    get 'kiteboarding', to: 'frontend#kiteboarding'

    get ':section/reservation/:code/:accomodation', to: 'frontend#reservation'

    post 'reserve', to: 'reservations#create'

    get 'price_activity/:name', to: 'reservations#price_activity'

    devise_for :users, skip: KepplerConfiguration.skip_module_devise

    mount KepplerContactUs::Engine, :at => '/', as: 'messages'

    mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'

    resources :admin, only: :index

    scope :admin do

      resources :legal_terms do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :rooms do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      get 'discount/:code', to: 'discounts#by_code', as: :discount_by_code
      resources :discounts do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

    	resources :users do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :quotes do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :activities do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :packages do
        resources :offers do
          get '(page/:page)', action: :index, on: :collection, as: ''
          delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
        end
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :reservations, except: :create do
        get '/charge', to: 'reservations#create_charge'
        get '/cancel', to: 'reservations#cancel_charge'
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :customers do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end
    end


    #errors
    match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
    match '/404', to: 'errors#not_found', via: :all
    match '/422', to: 'errors#unprocessable', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all


    #dashboard
    mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'
  end
end

app/models/legal_term.rb
#Generado por keppler
require 'elasticsearch/model'
class LegalTerm < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      description:  self.description.to_s,
    }.as_json
  end

end
#LegalTerm.import

app/controllers/legal_terms_controller.rb
#Generado con Keppler.
class LegalTermsController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_legal_term, only: [:show, :edit, :update, :destroy]

  # GET /legal_terms
  def index
    legal_terms = LegalTerm.searching(@query).all
    @objects, @total = legal_terms.page(@current_page), legal_terms.size
    redirect_to legal_terms_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /legal_terms/1
  def show
  end

  # GET /legal_terms/new
  def new
    @legal_term = LegalTerm.new
  end

  # GET /legal_terms/1/edit
  def edit
  end

  # POST /legal_terms
  def create
    @legal_term = LegalTerm.new(legal_term_params)

    if @legal_term.save
      redirect_to @legal_term, notice: 'Legal term was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /legal_terms/1
  def update
    if @legal_term.update(legal_term_params)
      redirect_to @legal_term, notice: 'Legal term was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /legal_terms/1
  def destroy
    @legal_term.destroy
    redirect_to legal_terms_url, notice: 'Legal term was successfully destroyed.'
  end

  def destroy_multiple
    LegalTerm.destroy redefine_ids(params[:multiple_ids])
    redirect_to legal_terms_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legal_term
      @legal_term = LegalTerm.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def legal_term_params
      params.require(:legal_term).permit(:description)
    end
end

app/helpers/legal_terms_helper.rb
module LegalTermsHelper
end

app/views/legal_terms/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.book.css_class("md-light") 
		Terminos Legales
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/legal_terms/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to legal_terms_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @legal_term do |f|
					.row
						= f.input :description, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/legal_terms/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, LegalTerm
			= link_to edit_legal_term_path(@legal_term), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink"=>true do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.book.css_class("md-light") 
		Terminos Legales
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= @legal_term.description.html_safe
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/legal_terms/_listing.html.haml
%tr{ id: "row-#{legal_term.id}" }
	- if can? :destroy_multiple, LegalTerm
		%td.item-check{style:"width: 10%"}
			= link_to "", legal_term_path(legal_term), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{legal_term.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{legal_term.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{legal_term.id}" }

	%td{style:"width: 90%"}	
		= link_to "", legal_term_path(legal_term, search: @query), remote: true, class: "show-row" 
		%span	
			Terminos legales de la reservación
								
	%td{style:"width: 5%"}		
		= link_to legal_term_path(legal_term), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/legal_terms/edit.html.haml
= title "Legal_terms - editar | #{@legal_term.id}"
= render 'form'

app/views/legal_terms/index.html.haml
= title("Legal_terms - Listado")
= header_information do
	= "Terminos Legales"
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_legal_term_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |legal_term|
				= render 'listing', legal_term: legal_term
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado legal_terms.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_legal_term_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/legal_terms/new.html.haml
= title "Legal_terms - Nuevo"
= render 'form'

app/views/legal_terms/show.html.haml
= title "Legal_terms | #{@legal_term.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, LegalTerm
				= link_to legal_term_path(@legal_term), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, LegalTerm
				= link_to edit_legal_term_path(@legal_term), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink"=>true do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to legal_terms_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.description")
					.display-value.fs-body-1.tc-black-2= @legal_term.description.to_s.html_safe

app/views/legal_terms/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@legal_term.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");