config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en/ do
    root to: 'frontend#index'

    get 'discover', to: 'frontend#discover'

    get 'diving', to: 'frontend#diving'

    get 'fishing', to: 'frontend#fishing'

    get 'kiteboarding', to: 'frontend#kiteboarding'

    get ':section/reservation/:code/:accomodation', to: 'frontend#reservation'

    post 'reserve', to: 'reservations#create'

    get 'price_activity/:name', to: 'reservations#price_activity'

    devise_for :users, skip: KepplerConfiguration.skip_module_devise

    mount KepplerContactUs::Engine, :at => '/', as: 'messages'

    mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'

    resources :admin, only: :index

    scope :admin do

      resources :legal_terms do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :rooms do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      get 'discount/:code', to: 'discounts#by_code', as: :discount_by_code
      resources :discounts do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

    	resources :users do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :quotes do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :activities do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :packages do
        resources :offers do
          get '(page/:page)', action: :index, on: :collection, as: ''
          delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
        end
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :reservations, except: :create do
        get '/charge', to: 'reservations#create_charge'
        get '/cancel', to: 'reservations#cancel_charge'
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :customers do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end
    end


    #errors
    match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
    match '/404', to: 'errors#not_found', via: :all
    match '/422', to: 'errors#unprocessable', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all


    #dashboard
    mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'
  end
end

app/models/room.rb
#Generado por keppler
require 'elasticsearch/model'
class Room < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_many :room_covers, :dependent => :destroy
  accepts_nested_attributes_for :room_covers, reject_if: :all_blank, allow_destroy: true
  
  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:name] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name.to_s,
      description:  self.description.to_s,
    }.as_json
  end

end
#Room.import

app/controllers/rooms_controller.rb
#Generado con Keppler.
class RoomsController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  def index
    rooms = Room.searching(@query).all
    @objects, @total = rooms.page(@current_page), rooms.size
    redirect_to rooms_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /rooms/1
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /rooms/1
  def update
    if @room.update(room_params)
      redirect_to @room, notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /rooms/1
  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  def destroy_multiple
    Room.destroy redefine_ids(params[:multiple_ids])
    redirect_to rooms_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def room_params
      params.require(:room).permit(:name, :description, room_covers_attributes: [:id, :url, :room_id, :_destroy])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.card_travel.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/rooms/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to rooms_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @room do |f|
					.row
						= f.input :name
						= f.input :description, input_html: {class: "materialize-textarea"}
						#room_covers
							%ul.collection{ style: "margin: 5px 10px;"}
								= f.simple_fields_for :room_covers do |image|
									= render 'room_cover_fields', f: image
								%center
									= link_to_add_association '+Add Image', f, :room_covers, class: "waves-light btn", style: "width: 100%"

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/rooms/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Room
			= link_to edit_room_path(@room), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.card_travel.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @room.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= @room.description
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/rooms/_listing.html.haml
%tr{ id: "row-#{room.id}" }
	- if can? :destroy_multiple, Room
		%td.item-check{style:"width: 10%"}
			= link_to "", room_path(room), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{room.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{room.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{room.id}" }

	%td{style:"width: 2%"}
		= material_icon.md_24.label_outline	
	%td{style:"width: 60%"}
		= link_to "", room_path(room, search: @query), remote: true, class: "show-row"
		%span
			= room.name
								
	%td{style:"width: 5%"}		
		= link_to room_path(room), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/rooms/_room_cover_fields.html.haml
%li.collection-item.avatar.nested-fields
	= image_tag f.object.url, width: "48px;", class: "circle", style: "margin-top: 15px;"
	= f.input :url, label: t("model.#{controller_name.singularize}.attributes.cover"), :as => :file_material, label: false, wrapper_html: { class: "file-field", id: "image-#{f.object.id}"}
	= link_to_remove_association  "<i class='material-icons md-24'>delete</i>".html_safe, f, class: "secondary-content", style: "margin-top: 15px;"
	- if f.object.created_at?
		:javascript
			$("#image-#{f.object.id} .file-path").val("#{f.object.url}")

app/views/rooms/edit.html.haml
= title "Rooms - editar | #{@room.id}"
= render 'form'

app/views/rooms/index.html.haml
= title("Rooms - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_room_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |room|
				= render 'listing', room: room
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado rooms.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_room_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/rooms/new.html.haml
= title "Rooms - Nuevo"
= render 'form'

app/views/rooms/show.html.haml
= title "Rooms | #{@room.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Room
				= link_to room_path(@room), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Room
				= link_to edit_room_path(@room), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to rooms_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card{style: "padding: 0px !important;"}		
			.card-image
				.slider
					%ul.slides
						- @room.room_covers.each do |img|
							%li
								= image_tag img.url	
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.name")
						.display-value.fs-body-1.tc-black-2= @room.name.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.description")
						.display-value.fs-body-1.tc-black-2= @room.description.to_s.humanize

app/views/rooms/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@room.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");